//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food_recipe()
        {
            this.comment = new HashSet<comment>();
            this.food_recipe_detail = new HashSet<food_recipe_detail>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_type { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public Nullable<int> pay_the_fee { get; set; }
        public string image { get; set; }
        public Nullable<int> author { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual account account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food_recipe_detail> food_recipe_detail { get; set; }
        public virtual type_recipe type_recipe { get; set; }
    }
}
