//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_recipe_detail
    {
        public int id { get; set; }
        public Nullable<int> id_food_recipe { get; set; }
        public Nullable<int> step { get; set; }
        public string content { get; set; }
    
        public virtual food_recipe food_recipe { get; set; }
    }
}
