//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class food_recipeEntities : DbContext
    {
        public food_recipeEntities()
            : base("name=food_recipeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<account_role> account_role { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<contact_feedback> contact_feedback { get; set; }
        public virtual DbSet<exam> exam { get; set; }
        public virtual DbSet<faq> faq { get; set; }
        public virtual DbSet<food_recipe> food_recipe { get; set; }
        public virtual DbSet<food_recipe_detail> food_recipe_detail { get; set; }
        public virtual DbSet<register> register { get; set; }
        public virtual DbSet<type_recipe> type_recipe { get; set; }
    }
}
